JRodriguez-1998/Superandome_-_AppFinal

app/src/main/java/com/example/superandome_appfinal/Constantes/TipoUsuario.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java
se filtran los items del navigation drawer según una variable de tipo usuario. se creó un enum para los tipos de usuario
=> items segun tipo usuario

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/cargarEmocionDiaria.java, app/src/main/res/vistas/consultante/layout/fragment_cargar_emocion_diaria.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo.xml, app/src/main/res/vistas/consultante/layout/fragment_reporte_emocion.xml, app/src/main/res/vistas/consultante/layout/fragment_reporte_rutina.xml, app/src/main/res/vistas/consultante/layout/nav_header_navigation_drawer_consultante.xml
Buenas, desarrolle el panel. El mismo se usa de ejemplo en la pantalla de registrar emoción diaria
=> Desarrollo diagologo/panel

app/src/main/java/com/example/superandome_appfinal/Entidades/Consejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/sugerirConsejo_profesional.java, app/src/main/res/vistas/consultante/layout/fragment_sugerir_consejo.xml, app/src/main/res/vistas/profesional/layout/fragment_sugerir_consejo_profesional.xml
Ya quedan las validaciones realizadas ya listas para cuando se pueda conectar a la BD
=> Logica: sugerir consejo consultante

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/sugerirConsejo_profesional.java, app/src/main/res/vistas/consultante/layout/fragment_sugerir_consejo.xml, app/src/main/res/vistas/profesional/layout/fragment_sugerir_consejo_profesional.xml
Ya quedan las validaciones realizadas ya listas para cuando se pueda conectar a la BD
=> Logica: sugerir consejo Profesional

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/configurarHorario.java, app/src/main/res/values/strings.xml, app/src/main/res/vistas/consultante/layout/fragment_configurar_horario.xml
Logica para la pantalla de configurar horario, a la espera de la conexion de la BD
=> ConfigurarHorario

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java, app/src/main/res/vistas/layout/activity_login.xml
Codigo primitivo para ingresar al respectivo usuario, enviando el tipo hacia el navigation_drawer
=> Logica LOGIN

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoSugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Entidades/Consejo.java, app/src/main/java/com/example/superandome_appfinal/Entidades/Estado.java, app/src/main/java/com/example/superandome_appfinal/Entidades/TipoConsejo.java, app/src/main/java/com/example/superandome_appfinal/IServices/ConsejoService.java, app/src/main/java/com/example/superandome_appfinal/Services/TipoConsejoServiceImpl.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java, app/src/main/res/vistas/consultante/layout/fragment_dialogo.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_sugerir_consejo.xml
ya conectado a la bd, guarda el consejo sugerido
=> logica sugerir consejo consultante

.idea/misc.xml, app/src/main/java/com/example/superandome_appfinal/Daos/ItemDaoImpl.java, app/src/main/java/com/example/superandome_appfinal/IDaos/ItemDao.java, app/src/main/java/com/example/superandome_appfinal/IServices/ItemService.java, app/src/main/java/com/example/superandome_appfinal/Services/ItemServiceImpl.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/rutinaDiaria.java, app/src/main/res/vistas/consultante/layout/fragment_rutina_diaria.xml
=> Carga lista rutina

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/homeConsultante.java
Ya muestra el consejo diario y va cambiando por cada dia
=> Consejos diarios

app/src/main/java/com/example/superandome_appfinal/Constantes/TipoConsejoEnum.java, app/src/main/java/com/example/superandome_appfinal/Daos/ConsejoDaoImpl.java, app/src/main/java/com/example/superandome_appfinal/IDaos/ConsejoDao.java, app/src/main/java/com/example/superandome_appfinal/IServices/ConsejoService.java, app/src/main/java/com/example/superandome_appfinal/Services/ConsejoServiceImpl.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/homeConsultante.java
se arreglo para que muestre consejos diferentes por dia y para usuario distintos
=> fix consejo

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogo.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoCambiarPass.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoCargarEmocion.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoConfHorario.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoSugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoUserConsultanteRegistrado.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/pregunta_seguridad.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/recuperarPassword.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java, app/src/main/res/vistas/consultante/layout/activity_recuperar_password.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_cambiar_pass.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_cargar_emocion.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_conf_horario.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_sugerir_consejo.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_usuario_registrado.xml, app/src/main/res/vistas/consultante/layout/fragment_pregunta_seguridad.xml
Se creo un dialogo para ingresar la contraseña nueva. se realizaron todas las validaciones correspondieentes(respuesta correcta, pregunta elegida, campos vacios)
=> Recuperar contraseña: consultante

.idea/misc.xml, app/src/main/java/com/example/superandome_appfinal/Daos/ItemUsuarioDaoImpl.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoRutinaConfigurada.java, app/src/main/java/com/example/superandome_appfinal/IDaos/ItemUsuarioDao.java, app/src/main/java/com/example/superandome_appfinal/IServices/ItemUsuarioService.java, app/src/main/java/com/example/superandome_appfinal/Services/ItemUsuarioServiceImpl.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/rutinaDiaria.java, app/src/main/res/vistas/consultante/layout/fragment_dialogo_rutina.xml, app/src/main/res/vistas/consultante/layout/fragment_rutina_diaria.xml
Carga a la bd de registros rutinas y muestra cuales estan seleccionados. Carteles aclaratorios
=> Configuracion de rutina completada

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/cargarEmocionDiaria.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/configurarHorario.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/homeConsultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/recuperarPassword.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java
agrego el share para que mantenga la sesion
=> shares en pantalla

.idea/misc.xml, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoEncuesta.java, app/src/main/java/com/example/superandome_appfinal/Entidades/EncuestaUsuario.java, app/src/main/java/com/example/superandome_appfinal/IServices/EncuestaUsuarioService.java, app/src/main/java/com/example/superandome_appfinal/Services/EncuestaUsuarioServiceImpl.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/ingresarEncuesta.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java, app/src/main/res/values/strings.xml, app/src/main/res/vistas/consultante/layout/fragment_dialogo_encuesta.xml, app/src/main/res/vistas/consultante/layout/fragment_ingresar_encuesta.xml
Ingresa encuesta por usuario y muestra el nivel de ansiedad
=> Ingresar encuesta

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoSugerirContenido.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_text.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirContenido.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/sugerirContenido_profesional.java, app/src/main/res/vistas/consultante/layout/fragment_dialogo_sugerir_contenido.xml, app/src/main/res/vistas/profesional/layout/fragment_sugerir_contenido_profesional.xml
Sugerir contenido profesional con dialogo
=> Sugerir contenido profesional

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_text.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_video.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirContenido.java, app/src/main/res/vistas/consultante/layout/fragment_multimedia_video.xml
=> Comienzo logica video

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_text.java
=> leer archivos multimedia

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/activity_altaConsultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/cargarEmocionDiaria.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/configurarHorario.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/homeConsultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/ingresarEncuesta.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_text.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/recuperarPassword.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/reporteEmocion.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/reporteRutina.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/rutinaDiaria.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/rutina_diaria_seguimiento.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirContenido.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/altaProfesional.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/aprobarConsejo_director.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/cambiar_password.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/homeDirector.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java
=> validaciones de errores

app/src/main/java/com/example/superandome_appfinal/Dialogos/derivarRechazarConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/derivarConsejo_profesional.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/sugerirConsejo_profesional.java, app/src/main/res/vistas/profesional/layout/cardview_consejo.xml, app/src/main/res/vistas/profesional/layout/fragment_derivar_consejo.xml
Se arreglo el espacio que existia entre los consejos enviados por el consultante,  al derivar un consejo al director se actualiza la lista. Si no hay consejos para derivar se muestra mensaje. Cuando un profesional deriva consejo ya no se muestra para el, sino solo director
=> Fix Recycler

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoAprobarConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirConsejo.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/sugerirContenido.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/aprobarConsejo_director.java, app/src/main/res/vistas/director/layout/fragment_aprobar_consejo.xml
Actualiza la lista a medida que se aprueba y rechazan contenidos, tambien se arreglo el espaciado que existia por cada item de esta lista. Si no hay contenido para aprobar se muestra cartel
=> Fix aprobar contenido

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoCambiarPass.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/activity_altaConsultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/recuperarPassword.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/altaProfesional.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/cambiar_password.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/cambiar_password_profesional.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java
contraseñas y validaciones hash
=> contraseñas y validaciones hash

app/src/main/java/com/example/superandome_appfinal/Dialogos/derivarRechazarConsejo.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoAprobarConsejo.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoCambiarPass.java, app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoCargarEmocion.java
agregados toast en catchs faltantes
=> agregados toast en catchs faltantes

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/superandome_appfinal/Helpers/Workmanagernoti.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java, app/src/main/java/com/example/superandome_appfinal/Vistas/activity_login.java, app/src/main/java/com/example/superandome_appfinal/Vistas/splash.java, app/src/main/res/vistas/consultante/layout/activity_splash.xml, app/src/main/res/vistas/consultante/values/strings.xml
Ya se puede ejecutar notificaciones si la app esta cerrada
=> Notificacion al ejecutar el onPause

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/navigation/mobile_navigation.xml, app/src/main/res/vistas/consultante/layout/fragment_multimedia_audio.xml, app/src/main/res/vistas/consultante/values/strings.xml
=> modificacion detalles audio

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_video.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/aprobarContenido_director.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/derivarContenido_profesional.java, app/src/main/res/navigation/mobile_navigation.xml, app/src/main/res/vistas/consultante/layout/fragment_multimedia_video.xml, app/src/main/res/vistas/director/layout/fragment_multimedia_video_director.xml, app/src/main/res/vistas/profesional/layout/fragment_multimedia_video_profesional.xml
=> arreglado videoview

app/src/main/res/vistas/consultante/layout/fragment_ingresar_encuesta.xml
Había choise repetidos, ahora esta todo en orden
=> Fix encuesta

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/navigationDrawer_consultante.java
se valido que previamente responda al menos una vez alguna encuesta para acceder al contenido multimedia
=> Validación responder encuesta

app/src/main/java/com/example/superandome_appfinal/Dialogos/dialogoSugerirContenidoProf.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/sugerirContenido_profesional.java, app/src/main/res/vistas/consultante/layout/fragment_dialogo_sugerir_contenido_prof.xml, app/src/main/res/vistas/consultante/values/strings.xml
solucionado el problema, ahora muestra el mensaje correspondiente y te deriva al home de profesional
=> FIX sugerir contenido profesional

app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/multimedia_audio.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Director/multimedia_audio_director.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Profesional/multimedia_audio_profesional.java
se corrigió el error que causaba que se siga reproduciendo el audio, y se corrigieron los fondos de los reproductores de consultante y director
=> parar audio cuando sale de reproductor

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/superandome_appfinal/Helpers/AlarmReceiver.java, app/src/main/java/com/example/superandome_appfinal/Vistas/Consultante/configurarHorario.java
se setea una alarma al configurar horario carga de emociom
=> desarrollo lanzar noti
